services:
  house-agent:
    build:
      context: .
      dockerfile: Dockerfile.agent
    container_name: house-agent
    restart: unless-stopped
    volumes:
      - ./.env:/app/.env
      - ./prompts:/app/prompts
      - chroma-data:/app/chroma_data
  sensor-collector:
    build:
      context: .
      dockerfile: Dockerfile.collector
    container_name: sensor-collector
    restart: unless-stopped
    volumes:
      - ./.env:/app/.env
      - ./house_agent.log:/app/house_collector.log

volumes:
  chroma-data:
    driver: local
