services:
  house-agent:
    build:
      context: .
      dockerfile: Dockerfile.agent
    container_name: house-agent
    restart: unless-stopped
    volumes:
      - ./.env:/app/.env
      - ./prompts:/app/prompts
      - ./config:/app/config
      - chroma-data:/app/chroma_data
  sensor-collector:
    build:
      context: .
      dockerfile: Dockerfile.collector
    container_name: sensor-collector
    restart: unless-stopped
    volumes:
      - ./.env:/app/.env
      - ./house_agent.log:/app/house_collector.log
  dashboard:
    build:
      context: .
      dockerfile: Dockerfile.dashboard
    container_name: dashboard
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes:
      - ./.env:/app/.env
    environment:
      - FLASK_ENV=production

volumes:
  chroma-data:
    driver: local
