version: "2"
services:
  house-agent:
    build:
      context: .
      dockerfile: Dockerfile.agent
    container_name: house-agent
    restart: unless-stopped
    volumes:
      - ./.env:/app/.env
      - ./housebot_prompt.txt:/app/housebot_prompt.txt
      - ./house_agent.log:/app/house_agent.log
  sensor-collector:
    build:
      context: .
      dockerfile: Dockerfile.collector
    container_name: sensor-collector
    restart: unless-stopped
    volumes:
      - ./.env:/app/.env
      - ./house_agent.log:/app/house_collector.log