version: "2"
services:
  house-agent:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: house-agent
    restart: unless-stopped
    volumes:
      - ./.env:/app/.env
      - ./housebot_prompt.txt:/app/housebot_prompt.txt